// for naming colors
// https://chir.ag/projects/name-that-color/#6195ED

export const COLORS = {
  DEEP_SEA: "#02875A",
  NILE_BLUE: "#172B4D",
  TIA_MARIA: "#DE350F",
  GIGAS: "#5243AA",
  LOCHMARA: "#0179BF",
  MULBERRY: "#CD5A91",
  ATHENS_GRAY: "#EBECF0",
  SHUTTLE_GRAY: "#5E6C84",
  SILVER: "#C4C4C4",
  WHITE: "#FFFFFF",
  BLACK: "#000000",
  ALLPORTS: "#026AA7",
};

export const THEME = {
  TEXT_PRIMARY: COLORS.NILE_BLUE,
  TEXT_SECONDARY: COLORS.WHITE,
  PRIMARY_CTA: COLORS.ALLPORTS,
};
