import { COLORS } from "../../values/colors";

export const boardLists = [
  {
    id: "ioehrfeojd",
    title: "board 1",
    boardColor: COLORS.LOCHMARA,
    cardLists: [
      {
        id: "2345678",
        title: "list 1",
        cards: [
          { id: "pokerofijerfe", text: "text 1" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
          { id: "pokerofijerfepokerf", text: "text 2" },
        ],
      },
      { id: "dfpojkew2345678", title: "list 2", cards: [] },
    ],
  },
  {
    id: "ioehrfeojopejrfd",
    title: "board 2",
    boardColor: COLORS.LOCHMARA,
    cardLists: [{ id: "2345678eporkf", title: "list 3", cards: [] }],
  },
];
